### ISSUE TITLE
USBInjectAll causes KP

### ISSUE THREAD

**Issue by 123marvin123** [blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore#1]
Hi,

thank you for the great guide. I have an Z390 AORUS PRO WiFi with a i5-9600k and if I load the USBInjectAll kext in open core, my system panics immediately. Is this a known issue?

**Comment by blacklizard** [comment]
> Hi,
> 
> thank you for the great guide. I have an Z390 AORUS PRO WiFi with a i5-9600k and if I load the USBInjectAll kext in open core, my system panics immediately. Is this a known issue?

Hi.. do you have the panic log? A video should be good.

**Comment by 123marvin123** [comment]
![IMG_0643](https://user-images.githubusercontent.com/7266447/79955656-61846100-847f-11ea-8fe5-3f6269f8a3b3.jpeg)

Hi, I can boot and install just fine without the UsbInjectAll. Please see the kernel panic in the picture. I also did a BIOS Update to F12c today but the kernel panic still occurs (also tried with F11 before, using your recommended settings).

**Comment by blacklizard** [comment]
where did you download the usbinjectall from?

**Comment by 123marvin123** [comment]
I downloaded it here: https://bitbucket.org/RehabMan/os-x-usb-inject-all/downloads/

I tried the two newest versions but they did not work. Where is your UIA from?

**Comment by blacklizard** [comment]
im using the same, but in order to solve this, what i would need is a video recording of the boot process until the kernal panic, that image does not contain full log, it could be acpi issue, Also will need your original DSDT dump( you can use clover to dump)
