### ISSUE TITLE
Upcoming Big Sur Update

### ISSUE THREAD

**Issue by 123marvin123** [blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore#17]
Hi,

I have seen that you have already experimented with the Big Sur Beta on your Hackintosh. Can you give us a short briefing on what to watch out for when doing the final update? Are there any special settings in OpenCore / BIOS or pitfalls when installing Big Sur compared to Catalina?

**Comment by blacklizard** [comment]
Hi..

I've tested the config(0.6.3) with 11.0.1 beta, it works without issue.

Before upgrading your main SSD, experiment with Big Sur on a different SSD. If you feel all apps that you use already supported in Big Sur, then update your main SSD.

**Comment by 123marvin123** [comment]
Thanks, everything went fine.
