### ISSUE TITLE
USB stops working randomly

### ISSUE THREAD

**Issue by 123marvin123** [blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore#19]
Hi,

I hope somebody can help me. My USB ports sometimes stop working suddenly. It's really random and on some days it occurs like 2-3x a day and sometimes only once a week. The issue has been occurring persistently since I own this Hackintosh and I have to reboot the machine because bluetooth stops working too since it is connected to the usb interface on the mainboard. It seems like the ports still have power but no data. I already tried a lot of options to fix this problem but it is not reproducible (afaik) and I basically just have to wait like 2 weeks after I try something new in hope that the issue disappeared. I already tried these settings:

- Regenerate my USBMap according to a German guide using Hackintool. The map works fine and is exactly behaving like I want it to. I don't think that the usb map is the issue. Maybe the generated acpi files?
- I tried to use the acpi files from this repo, but the issue still persisted.
- I tried to change bios settings regarding usb options, but nothing helped.
- I tried to use the exact config.plist from this repo, but it changed nothing.

There was a phase where this issue did not occur for like 2-3 months, but I have no idea why and if I changed anything that made the issue go away.

Does anybody have tips or experienced similar problems? I will provide my acpi files and usb map for now. I can provide more files if needed:
[Troubleshooting.zip](https://github.com/blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore/files/5590312/Troubleshooting.zip)

**Comment by blacklizard** [comment]
please attach your efi folder. You may try disconnect your front panel usb connector from the motherboard and see if the issue persist.

**Comment by blacklizard** [comment]
also please provide unpatched dsdt dump

**Comment by 123marvin123** [comment]
Here is everything:

[EFI.zip](https://github.com/blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore/files/5591259/EFI.zip)
[DSDT.aml.zip](https://github.com/blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore/files/5591265/DSDT.aml.zip)

Please keep the following in mind:
- "Resources" folder has been deleted in the EFI.zip due to file size.
- I changed SMBios to iMacPro1,1 and disabled the internal graphics unit because I have a different graphics setup than you do. Since the change to iMacPro1,1 the graphics are running good and the usb issue was already present before the SMBios change.
- The serial number and other secret keys have been removed from the config.plist (e.g. board number)
- Add ACPI files have been generated by Hackintool / SSDTTime

**Comment by blacklizard** [comment]
Remove the generated `SSDT-EC-USBX.aml` and `SSDT-EC.aml` and use the attached `SSDT-EC-USBX.aml`, its based on your DSDT dump, not generated.
[SSDT-EC-USBX.aml.zip](https://github.com/blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore/files/5591495/SSDT-EC-USBX.aml.zip)

Quick question, when usb stoped working, does all port stopped working or just a specific ports? If only 4 usb2 port and internal usb2 not working, probably you have fried usb controller

**Comment by 123marvin123** [comment]
Thanks, I will try your EC-USBX. Regarding your question: No, everything stops working completely. Both USB2.0 and USB3.x ports, I don't think the controller is fried. If I attach the keyboard manually via usb cable instead of bluetooth to any port, it will not work.

**Comment by blacklizard** [comment]
do update back how its, but a quick google search revealed it might be faulty processor.. Same symptom as your issue
https://www.olarila.com/topic/6063-all-usb-ports-freeze-randomly-on-mojave/?do=findComment&comment=94702

**Comment by 123marvin123** [comment]
Yes, I have build some Hackintoshes in the past too and never encountered anything like this. I hope it is not a faulty CPU, maybe it is related to some cpu and memory overclocking I did. I've undone the EC-USBX file now and removed the overclock in bios, let's see how it goes. I don't think it will have much of an effect because the OC was stable so far.

**Comment by 123marvin123** [comment]
Nope, just crashed even without the OC. Maybe it's really the CPU but it's hard to believe honestly, because it's running fine and was brand new when I bought it.

**Comment by blacklizard** [comment]
Its time to RMA the cpu

**Comment by jansure** [comment]
> Hi,
> 
> I hope somebody can help me. My USB ports sometimes stop working suddenly. It's really random and on some days it occurs like 2-3x a day and sometimes only once a week. The issue has been occurring persistently since I own this Hackintosh and I have to reboot the machine because bluetooth stops working too since it is connected to the usb interface on the mainboard. It seems like the ports still have power but no data. I already tried a lot of options to fix this problem but it is not reproducible (afaik) and I basically just have to wait like 2 weeks after I try something new in hope that the issue disappeared. I already tried these settings:
> 
>     * Regenerate my USBMap according to a German guide using Hackintool. The map works fine and is exactly behaving like I want it to. I don't think that the usb map is the issue. Maybe the generated acpi files?
> 
>     * I tried to use the acpi files from this repo, but the issue still persisted.
> 
>     * I tried to change bios settings regarding usb options, but nothing helped.
> 
>     * I tried to use the exact config.plist from this repo, but it changed nothing.
> 
> 
> There was a phase where this issue did not occur for like 2-3 months, but I have no idea why and if I changed anything that made the issue go away.
> 
> Does anybody have tips or experienced similar problems? I will provide my acpi files and usb map for now. I can provide more files if needed: [Troubleshooting.zip](https://github.com/blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore/files/5590312/Troubleshooting.zip)

hi,guy, my hackintosh includes macos 12.6.3、intel 13900K CPU 、Asus Z790-P wifi Motherboard problem is the same as yours.I ask you to your this problem whether has been resolved? If you have resolved it, please teach me.Thanks.

**Comment by 123marvin123** [comment]
@jansure The issue was a faulty bluetooth module (the ones that come from real macs). I removed the module and the usb issue never occurred again.

**Comment by jansure** [comment]
> @jansure The issue was a faulty bluetooth module (the ones that come from real macs). I removed the module and the usb issue never occurred again.



> @jansure The issue was a faulty bluetooth module (the ones that come from real macs). I removed the module and the usb issue never occurred again.

Thank you very much for your response and reminder. Could you please specify which Bluetooth submodule is causing the issue? How can I fix or remove it? Please let me know. Thank you.

**Comment by jansure** [comment]
> @jansure The issue was a faulty bluetooth module (the ones that come from real macs). I removed the module and the usb issue never occurred again.


Hello, can you see my comment? Did you remove the Bluetooth hardware device or the Apple-built Bluetooth driver?

**Comment by jansure** [comment]
@123marvin123 Thank you very much for your response and reminder. Could you please specify which Bluetooth submodule is causing the issue? How can I fix or remove it? Please let me know. Thank you.

**Comment by 123marvin123** [comment]
It was an AirPort Card out of a real MacBook, wrapped in a PCIe-Adapter. It had nothing to do with the motherboard itself.

**Comment by bjzhangshuai** [comment]
I have already replaced the Broadcom card that supports AirDrop on my Hackintosh with an Intel A200 series card, but I still experience a phenomenon where all USB devices disconnect every 10 days. My machine is configured with an Asus Z790-itx motherboard, two 48GB DDR5 RAM modules ，Acer 7000 series  ssd, and a 13900K CPU. Additionally, I have another motherboard, the Asus Z790-P wifi, which exhibits the same issue, as does the Gigabyte Aorus Z790 Master X, which experiences USB device disconnections every 9 days. Could you please help me analyze this issue? Thank you very much.
