### ISSUE TITLE
Any plans to update to bios 12k?

### ISSUE THREAD

**Issue by TreyM** [blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore#20]
Gigabyte enabled resizable bar in the latest bios (12k) update. I'm gonna give it a go and flash, but I'm not sure how macOS is gonna behave  if these changes to the bios were significant.

**Comment by blacklizard** [comment]
@TreyM dont think this will improve any performance in macOS, i will update later this week and update the doc when OC 0.6.7 is released

**Comment by TreyM** [comment]
No, I agree with you. I doubt it will affect anything in macOS. I dual boot windows 10, so the feature was more for gaming purposes on Windows 10 as I have a 6800 XT.
