### ISSUE TITLE
there are some problem for me

### ISSUE THREAD

**Issue by javasouls** [blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore#24]
I use your config and  "aml" for my pc because the same hardware。but I found the front USB3.1 show me USB2.0 480mpbs whem plugmy 3.0 device in，so，are you the same？my macOS is monterey 12.0 beta

however，thank you very much！

**Comment by blacklizard** [comment]
no such issue. Double check if your mapping is correct, or use the mapping provided in this repo. Also verify if your usb device is indeed capable of 5Gbps, some usb 3 device only capable of usb2 speed but advertised as usb3.

![Uploading Screenshot 2021-06-28 at 11.59.52 PM.png…]()
