### ISSUE TITLE
CPU Management & Sensors

### ISSUE THREAD

**Issue by gbasile** [blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore#5]
Thanks for the guide, it was a great point of reference to setup my Hackintosh

If I use iMac19,1 as a system reference with the same motherboard and an i9 9900k the system runs at 50% of the CPU and I don't get much reading of the temperature and fans sensors. 
Switching to iMac18,3 managed the CPU to work at its right frequencies and I have now much more readings from the sensors. 

In both cases, I have the already patched the BISO CFG and adjusted the CFG settings. 

Have you experienced something similar on your i5? Maybe you have more power to unlock if you have the same issue as I did. 

(for reference, my setup is here: https://github.com/gbasile/hackintosh-latte

PD: This is not a real issue, feel free to close it.

**Comment by blacklizard** [comment]
All i can think of is that you have wrong `SSDT-PLUG`, did you match your bios device name to the SSDT? You can get the device name from SSDT dump. Another way to validate is by using clover to test, set `PluginType=1` in clover and see if there is same issue

**Comment by gbasile** [comment]
After writing this issue I decided to give a try again to iMac 19,1 and it worked 😳
I can tell that the sensors are not updating at the same frequency as with 18,3 but it's not a big deal. 

Thanks for your repo! This is my first hackintosh and I used it as a reference multiple time for different steps of the configuration

**Comment by blacklizard** [comment]
Glad that it worked for you. Do keep in mind, even sensor information is not reliably available in an actually mac, i never really bothered about it. Do keep an eye on this repo, will be updating to OC 0.5.8 in few days time
