### ISSUE TITLE
能不能上传完整的EFI目录

### ISSUE THREAD

**Issue by microzhang715** [blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore#6]
能不能上传完整的EFI目录，省去找各种kext的时间

**Comment by blacklizard** [comment]
Hi, i think its better to down the kext from the actual repo, adding kext here will make it difficult to keep it updated with upstream repo, on next 0.5.8 update, i will link it to the individual repo

**Comment by microzhang715** [comment]
if link to kext ,I think it will be better and helpful to me! 
thkan you very much, I can enjoy macos now
