### ISSUE TITLE
USB Type-C not works

### ISSUE THREAD

**Issue by zhangtai** [blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore#7]
Jeevan, Thanks very much for providing such useful guide, this is my first time using opencore, since the upgrade to macOS 10.15.5 failed with Clover. I copied most of the files you provided, and download with links. All working fine, but found Type-C is not working when connecting with USB disk or camera, do you have any advise? Thanks!

Files:

```console
└── EFI
   ├── BOOT
   │  └── BOOTx64.efi
   └── OC
      ├── ACPI
      │  ├── SSDT-EC-USBX.aml
      │  ├── SSDT-HPET.aml
      │  ├── SSDT-PLUG.aml
      │  └── SSDT-PMC.aml
      ├── Bootstrap
      │  └── Bootstrap.efi
      ├── config.plist
      ├── config_usb.plist
      ├── Drivers
      │  ├── OpenRuntime.efi
      │  └── VBoxHfs.efi
      ├── Kexts
      │  ├── AppleALC.kext
      │  ├── IntelMausi.kext
      │  ├── Lilu.kext
      │  ├── SMCBatteryManager.kext
      │  ├── SMCLightSensor.kext
      │  ├── SMCProcessor.kext
      │  ├── SMCSuperIO.kext
      │  ├── USBInjectAll.kext
      │  ├── USBPorts.kext
      │  ├── VirtualSMC.kext
      │  └── WhateverGreen.kext
      ├── OpenCore.efi
      ├── Resources
      │  ├── Audio
      │  ├── Font
      │  ├── Image
      │  └── Label
      └── Tools
         ├── modGRUBShell.efi
         ├── OpenShell.efi
         └── ResetSystem.efi
```

**Comment by 123marvin123** [comment]
Probably a problem with your USBPorts.kext. Have you mapped the ports yourself? Please keep in mind that macOS has a 15-ports limit, and the usb-c port might not be configured in the provided USBPorts kext. Also, which USB-C port are you actually referring to? The mainboard has one in the back (HS06 / SS06) and one available interface for a potential front port (HS01 / SS01).

**Comment by blacklizard** [comment]
like @123marvin123 mentioned, its probably your usbmap. Im guessing you either enable SS or HS, not both. Easy way to determine is to only enable 2 physical port interface, one for your keyboard and mouse and another one for your usb-c port.

enable the following

1. HS13 - For your usb and keyboard
2. HS06/SS06 - For your rear usb type c.

Then test if your usb type-c is working

**Comment by zhangtai** [comment]
@123marvin123 @blacklizard Thanks both for the promptly reply. I am using SS06 port, download the `USBPorts.kext` in the repo without any mapping, btw I am using the `config.plist` without any modification as well. As you [mentioned](https://github.com/blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore/blob/master/USBMAP.md#enabled-ports), the SS06 should already enabled rt?

**Comment by blacklizard** [comment]
@zhangtai if you use my usbmap kext, for read usb-c port, only usb3 device will work on that port, usb2 device will not work in that port. It will be easier if you could tell what device(make and model) that you are connecting to that port

**Comment by zhangtai** [comment]
It works! After a reboot, previous I connected the usb device when first installed with OpenCore without a reboot. After reboot, I connected again(and it not works firstly). I left my desktop and after I came back and wake it up, it works. 

Thanks again both! @blacklizard @123marvin123
