### ISSUE TITLE
BCM943602CS Unable to hibernate Issue

### ISSUE THREAD

**Issue by HueLiu** [blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore#9]
Hello,

My motherboard model, WiFi and Bluetooth are the same as yours and all functions work fine when I'm not in sleep status. 

But I try to sleep, it repeatedly and automatically starts lighting up. 

I have followed the corresponding tutorial to make my Bluetooth be internal. But it seems to me that it didn't work. However, I have tried to block the USB port for Bluetooth with Hackintool, the sleep was normal. 

![image](https://user-images.githubusercontent.com/19755727/85013868-e1852980-b197-11ea-968e-2318258f70ed.png)

![image](https://user-images.githubusercontent.com/19755727/85014075-31fc8700-b198-11ea-99c3-50cae2abfeb1.png)

Since you and I are using the same WiFi and Bluetooth, I would like to ask about your USBports.kext configuration! Or are there other ways you can work properly.

As a side note, my config.plist is the same as yours, the only difference is that I removed the `-v`.

Thank you ;)

**Comment by blacklizard** [comment]
@HueLiu it seems something wrong with your USB port mapping. You can try my usbport map kext and see if your sleep issue is resolved

[USBPorts.kext.zip](https://github.com/blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore/files/4798269/USBPorts.kext.zip)

**Comment by HueLiu** [comment]
> @HueLiu it seems something wrong with your USB port mapping. You can try my usbport map kext and see if your sleep issue is resolved
> 
> [USBPorts.kext.zip](https://github.com/blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore/files/4798269/USBPorts.kext.zip)

Thx, but it didn't work.

Since my BCM943602CS's Bluetooth is connecting to a USB 2.0 port (HS11). I'm not sure if this is the cause.

Anyway, thank you ;)

**Comment by 123marvin123** [comment]
@HueLiu Are you using an adapter for the BCM943602CS module?

**Comment by HueLiu** [comment]
> @HueLiu Are you using an adapter for the BCM943602CS module?

Yes, BCM943602CS with PCI-E and Bluetooth to USB 2.0.

May I ask if you have a good solution for this?

**Comment by 123marvin123** [comment]
Yes, this issue is related to the pci-e adapter having no proper power management for the card. This is often the case with cheap adapters, you need a proper adapter. Can you send an image of the adapter?

**Comment by HueLiu** [comment]
> Yes, this issue is related to the pci-e adapter having no proper power management for the card. This is often the case with cheap adapters, you need a proper adapter. Can you send an image of the adapter?

Here you go!

![image](https://user-images.githubusercontent.com/19755727/85020665-41cd9880-b1a3-11ea-94c8-6e997e06919b.png)

![image](https://user-images.githubusercontent.com/19755727/85020803-73466400-b1a3-11ea-8dce-e10fb6c2a81d.png)

I bought this adapter two years ago, but I didn't use it at that time. Of course, it is very cheap :P

Thank you~

**Comment by 123marvin123** [comment]
Yea, looks like a cheap adapter. The missing power management circuitry is probably the culprit here :)

**Comment by HueLiu** [comment]
> Yea, looks like a cheap adapter. The missing power management circuitry is probably the culprit here :)

Is there a way to make this adapter to sleep if I want to continue using it?

**Comment by 123marvin123** [comment]
> > Yea, looks like a cheap adapter. The missing power management circuitry is probably the culprit here :)
> 
> Is there a way to make this adapter to sleep if I want to continue using it?

Not that I know. The only solution is to prevent your system from going to sleep, which obviously is not optimal. I have tried multiple adapters and they were all bad. I am now using a commercial pre-made adapter + airport card and sleep is working fine. It's was pretty expensive though.

**Comment by HueLiu** [comment]
> > > Yea, looks like a cheap adapter. The missing power management circuitry is probably the culprit here :)
> > 
> > 
> > Is there a way to make this adapter to sleep if I want to continue using it?
> 
> Not that I know. The only solution is to prevent your system from going to sleep, which obviously is not optimal. I have tried multiple adapters and they were all bad. I am now using a commercial pre-made adapter + airport card and sleep is working fine. It's was pretty expensive though.

Right, thank you. It seems to be a Problem without solutions.

Btw, What is the model of your new adapter?

**Comment by blacklizard** [comment]
Some proper pci-e adaptor for BCM943602CS

https://www.aliexpress.com/item/32834221503.html
https://www.aliexpress.com/item/4000401848618.html
https://www.aliexpress.com/item/32829764429.html

**Comment by 123marvin123** [comment]
> > > > Yea, looks like a cheap adapter. The missing power management circuitry is probably the culprit here :)
> > > 
> > > 
> > > Is there a way to make this adapter to sleep if I want to continue using it?
> > 
> > 
> > Not that I know. The only solution is to prevent your system from going to sleep, which obviously is not optimal. I have tried multiple adapters and they were all bad. I am now using a commercial pre-made adapter + airport card and sleep is working fine. It's was pretty expensive though.
> 
> Right, thank you. It seems to be a Problem without solutions.
> 
> Btw, What is the model of your new adapter?

It's called fenvi T919 (sadly it's the BCM943602CD and only has Bluetooth 4.0).

> Some proper pci-e adaptor for BCM943602CS
> 
> https://www.aliexpress.com/item/32834221503.html
> https://www.aliexpress.com/item/4000401848618.html
> https://www.aliexpress.com/item/32829764429.html

Sadly, many of these suppliers are not sending the exact adapter that is displayed in the images. I bought 2 adapters and they were both not the ones that looked like the pictures, keep that in mind.

**Comment by HueLiu** [comment]
thank you guys～ @123marvin123 @blacklizard

**Comment by mistake1px** [comment]
@HueLiu 我和你一样的问题，淘宝上买的BCM943602CS，睡眠即醒。换了FV T919之后，完美解决～
